### ISSUE TITLE
Not working as expected

### ISSUE THREAD

**Issue by AyshwaryaRamakrishnan** [aflyen/spfx-extension-fullpagecanvas#1]
Hello,

I tried running this using gulp serve (after modifying serve.json to point to my site) and also deploying it - both communication and team site. Does not seem to work (neither on chrome nor on IE)
The top portion (below the app launcher) is still visible. Please help. Attached is the screenshot

![image](https://user-images.githubusercontent.com/12132097/52703892-63ae7e00-2fa5-11e9-970f-0c1511bc6665.png)

**Comment by aflyen** [comment]
Thanks for reaching out! Yes, a while back the structure of the headers was changed and that's the reason why it didn't work anymore. I have updated the code with a selector that works with the latest change. Please feel free to test it out again now.

**Comment by AyshwaryaRamakrishnan** [comment]
Excellent - works on communication site. Is it expected to behave the same on team site?

**Comment by AyshwaryaRamakrishnan** [comment]
Checked on team site - works if the page is set as welcome page. Thanks.
